### ISSUE TITLE
Cannot run StreamDeck, OSError: open failed

### ISSUE THREAD

**Issue by Xlaits** [timothycrosley/streamdeck-ui#101]
Error is as seen below. streamdeck cannot be run.

```Traceback (most recent call last):
  File "/home/xlaits/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/xlaits/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 266, in start
    for deck_id, deck in api.open_decks().items():
  File "/home/xlaits/.local/lib/python3.9/site-packages/streamdeck_ui/api.py", line 100, in open_decks
    deck.open()
  File "/home/xlaits/.local/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 122, in open
    self.device.open()
  File "/home/xlaits/.local/lib/python3.9/site-packages/StreamDeck/Transport/HIDAPI.py", line 48, in open
    self.hid.open_path(self.hid_info['path'])
  File "hid.pyx", line 72, in hid.device.open_path
OSError: open failed```

**Comment by Xlaits** [comment]
Ended up solving this by accident. udev wasn't assigning the stream deck the appropriate group.
