### ISSUE TITLE
Unable to open HID device.

### ISSUE THREAD

**Issue by Gotchfutchian** [timothycrosley/streamdeck-ui#160]
Currently using the AUR version of streamdeck-ui (via yay and Arch strata) and I canot open the program at all. Output listed below.
```
[gotchfutchian@gotchbox-bedrock ~]$ streamdeck
Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 33, in <module>
    sys.exit(load_entry_point('streamdeck-ui==1.1.2', 'console_scripts', 'streamdeck')())
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 645, in start
    items = api.open_decks().items()
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/home/gotchfutchian/.local/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/home/gotchfutchian/.local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 350, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/gotchfutchian/.local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.
Segmentation fault
[gotchfutchian@gotchbox-bedrock ~]$ 
```

Additional System information;
```
--------------------------------------   gotchfutchian@gotchbox-bedrock 
--------------------------------------   ------------------------------ 
--------------------------------------   OS: Bedrock Linux 0.7.23 Poki x86_64 
---\\\\\\\\\\\\-----------------------   Host: Alienware Aurora R9 1.0.13 
----\\\      \\\----------------------   Kernel: 5.13.19_1 
-----\\\      \\\---------------------   Uptime: 3 mins 
------\\\      \\\\\\\\\\\\\\\\\------   Packages: 502 (pacman), 513 (dpkg), 877 (xbps-query), 7 (flatpak) 
-------\\\                    \\\-----   Shell: bash 5.1.8 
--------\\\                    \\\----   Resolution: 2560x1440 
---------\\\        ______      \\\---   DE: Plasma 5.22.5 
----------\\\                   ///---   WM: KWin 
-----------\\\                 ///----   Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
------------\\\               ///-----   Icons: Humanity-Dark [Plasma], Humanity-Dark [GTK2/3] 
-------------\\\////////////////------   Terminal: konsole 
--------------------------------------   CPU: Intel i7-9700K (8) @ 4.900GHz 
--------------------------------------   GPU: NVIDIA GeForce RTX 2070 SUPER 
--------------------------------------   GPU: Intel CoffeeLake-S GT2 [UHD Graphics 630] 
                                         Memory: 1153MiB / 15835MiB 
```

**Comment by zanloy** [comment]
Did you do the udev steps in the [manual install steps](https://github.com/timothycrosley/streamdeck-ui#manual-installation)? By default non-root users don't have the appropriate permissions to directly access the HID devices without those steps.

**Comment by Gotchfutchian** [comment]
> Did you do the udev steps in the [manual install steps](https://github.com/timothycrosley/streamdeck-ui#manual-installation)? By default non-root users don't have the appropriate permissions to directly access the HID devices without those steps.

I cannot, as i use runit instead of systemd, and running streamdeck-ui says it cant connect to the X server

**Comment by Gotchfutchian** [comment]
> > Did you do the udev steps in the [manual install steps](https://github.com/timothycrosley/streamdeck-ui#manual-installation)? By default non-root users don't have the appropriate permissions to directly access the HID devices without those steps.
> 
> I cannot, as i use runit instead of systemd, and running streamdeck-ui says it cant connect to the X server
> 
> Edit; when i get a moment again, I will attempt to run it under sudo instead of doas, as doas was installed via the arch stratum and not void

Yep, just ran it with sudo and it works. Sorry bout all that.
