### ISSUE TITLE
wont start due to previous setup : is way to flush out previous

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#167]
I have had  streamdeck up and running an empty profile.
I import a profile and it wont start. 

I managed to trace it down to a few icon/images miss-named, which I fixed my copying and renaming icons.

How ever it is now refusing and I am not sure what the error means when launched from the cli.

`Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 33, in <module>
    sys.exit(load_entry_point('streamdeck-ui==1.1.2', 'console_scripts', 'streamdeck')())
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 675, in start
    items = api.open_decks().items()
  File "/usr/lib/python3.9/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/usr/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/usr/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 350, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/usr/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.
`
I have tried uninstalling and reinstalling Stremdeck-ui ... But still the error persists.

Is there a command to give toi do : Flush the imported profile? : Manualy delete files? ...

Short of reinstall the os(ArcoLinux) I see no way of fixing this now.

Possible to add command to flush/change import profile,  Streamdeck -flush?

**Comment by Data-007** [comment]
Another start trace  ->> whats wrong, how to fix.
`wait for device(s)
found 1
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/home/steve/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/steve/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 380, in start
    api.render()
  File "/home/steve/.local/lib/python3.9/site-packages/streamdeck_ui/api.py", line 357, in render
    deck.set_key_image(button_id, image)
  File "/home/steve/.local/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 169, in set_key_image
    raise IndexError("Invalid key index {}.".format(key))
IndexError: Invalid key index 16.
python: os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.
Aborted (core dumped)`

**Comment by dodgyrabbit** [comment]
This issue relates to the actual images you are using. Try a different image, or image format.
Your configuration is stored in `~/.streamdeck_ui.json`. You could delete it (backup first if you wish) and then launch. It will start with clean config so you can try with different images.
