### ISSUE TITLE
streamdeck program not launching

### ISSUE THREAD

**Issue by J-onasJones** [timothycrosley/streamdeck-ui#177]
I installed the program by following the instructions but when I enter the command "streamdeck" I get the following error message:
`(python3:9336): Gtk-WARNING **: 00:33:48.239: Theme parsing error: gtk.css:2:128: Failed to import: Error opening file /home/jonas_jones/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/maximized.css: No such file or directory
Traceback (most recent call last):
  File "/home/jonas_jones/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/jonas_jones/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 634, in start
    items = api.open_decks().items()
  File "/home/jonas_jones/.local/lib/python3.9/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/home/jonas_jones/.local/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 148, in open
    self.device.open()
  File "/home/jonas_jones/.local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 350, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/jonas_jones/.local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.
`
I am on Pop!_OS
Please Help, thanks in advance

**Comment by idoodler** [comment]
Having the same issue on PopOS

**Comment by Steiniche** [comment]
Seeing the same problem with PopOS 20.04.

The udev rules are in place and loaded.

libhidapi-libusb0 (0.9.0+dfsg-1) and libxcb-xinerama0 (1.14-2) is installed.

**Comment by dodgyrabbit** [comment]
Most likely cause is that something was missed in these steps:
https://github.com/timothycrosley/streamdeck-ui#manual-installation

Please reopen if the issue persists and provide as much detail as possible.
