### ISSUE TITLE
ImportError: /usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_cc_store_primary_cred, version krb5_3_MIT

### ISSUE THREAD

**Issue by cray12399** [timothycrosley/streamdeck-ui#181]
Hello, I am getting the following output when I try to run streamdeck-ui on my system:

```
Traceback (most recent call last):
  File "/home/chris/anaconda3/bin/streamdeck", line 33, in <module>
    sys.exit(load_entry_point('streamdeck-ui==1.1.2', 'console_scripts', 'streamdeck')())
  File "/home/chris/anaconda3/bin/streamdeck", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/chris/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/chris/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chris/anaconda3/lib/python3.8/site-packages/streamdeck_ui/gui.py", line 11, in <module>
    from PySide2 import QtWidgets
ImportError: /usr/lib/libgssapi_krb5.so.2: undefined symbol: k5_cc_store_primary_cred, version krb5_3_MIT
```
I installed it from the [AUR](https://aur.archlinux.org/packages/streamdeck-ui-git/) and I am on Arch Linux Kernel Version 5.15.11-zen1-1-zen.

How can I fix this error?

**Comment by cray12399** [comment]
Just removed anaconda and that fixed the problem. So, I guess this software isnt compatible with anaconda.

**Comment by cray12399** [comment]
Just removed anaconda and that fixed the problem. So, I guess this software isnt compatible with anaconda.
