### ISSUE TITLE
Streamdeck stops working after waking from suspend

### ISSUE THREAD

**Issue by cray12399** [timothycrosley/streamdeck-ui#184]
Whenever I wake my PC from sleep, the streamdeck service has to be restarted in order for my stream deck to work.

**Comment by MikeDrewitt** [comment]
I also have this issue. Here's the weird thing though. The process is still running in the background (though I don't have a way to check its logs), but if I kill it and attempt to reup the process, I'm greeted with this stack trace. 

```
Traceback (most recent call last):
  File "/usr/bin/streamdeck", line 33, in <module>
    sys.exit(load_entry_point('streamdeck-ui==1.1.2', 'console_scripts', 'streamdeck')())
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 675, in start
    items = api.open_decks().items()
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/api.py", line 106, in open_decks
    deck.reset()
  File "/usr/lib/python3.10/site-packages/StreamDeck/Devices/StreamDeckOriginalV2.py", line 111, in reset
    self.device.write_feature(payload)
  File "/usr/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 400, in write_feature
    return self.hidapi.send_feature_report(self.device_handle, payload)
  File "/usr/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 217, in send_feature_report
    raise TransportError("Failed to write feature report (%d)" % result)
StreamDeck.Transport.Transport.TransportError: Failed to write feature report (-1)
python: os/threads_posix.h:58: usbi_mutex_destroy: Assertion `pthread_mutex_destroy(mutex) == 0' failed.
python: os/threads_posix.h:46: usbi_mutex_lock: Assertion `pthread_mutex_lock(mutex) == 0' failed.
[1]    7458 abort (core dumped)  streamdeck
```

It seems to be that something is locking and not being released when the process is killed, then restarted, but I'm really not to sure. 

Rebooting fixes the issue, but that's obviously not ideal.

**Comment by tassyv** [comment]
https://github.com/timothycrosley/streamdeck-ui/issues/4

**Comment by dodgyrabbit** [comment]
Closing as duplicate. This can be fixed, will need an fix from the underlying library first.
