### ISSUE TITLE
darkages upgrading python >3.9.9

### ISSUE THREAD

**Issue by Data-007** [timothycrosley/streamdeck-ui#197]
Sorry to be pest Timothy-/-Pieter

I have python 3.9.9 installed and have managed to install and run streamdeck, great err no sorry.

I have a number off problems now with other applications notably Terminator(prompt), wont start and others.
Python 3.10 has now been out for a while now, Can Either off you  upgrade this marvelous wonderful project to
version which uses 3.10, or 3.10.2 which is more current

The error I get from streamdeck is shown below .
<a target="_blank" href="https://imageshack.com/i/pmKublkop"><img src="https://imagizer.imageshack.com/v2/xq90/922/Kublko.png" border="0"></a>

Iam on Arcolinux and arch based distro.

**Comment by dodgyrabbit** [comment]
A [new version](https://github.com/timothycrosley/streamdeck-ui/blob/master/CHANGELOG.md#113---2-feb-2022) was released a few days ago. This means it will work fine with Python 3.10 now and you don't need to be on 3.9 (the dark ages are over!).

However, looking at the error - you must **not** be running the released version (1.1.3) because SVG support (using the cairosvg library) was only added after that.

Are you still doing the install directly via a reference to git? I would recommend you uninstall that and install it using pip from the pypi repository (as per the regular installation instructions).

**Comment by Data-007** [comment]
Hi Pieter
You closed the previous one I cant find it to do manual install. Ive done an install from source.
   **_189  2022-02-05 11:34:58     python-elgato-streamdeck 0.8.5-2_**
   190  2022-02-05 11:35:36     pyside2 5.15.2.1-1
   191  2022-02-05 11:35:36     python-evdev 1.4.0-3
   192  2022-02-05 11:35:36     python-hidapi 0.11.0.2-3
   193  2022-02-05 11:35:36     python-pynput 1.7.6-1
   194  2022-02-05 11:35:36     python-shiboken2 5.15.2.1-1
   195  2022-02-05 11:35:36     python-xlib 0.31-3
   **_196  2022-02-05 11:35:36     streamdeck-ui-git r298.1636020-1_**
   197  2022-02-05 14:14:20     ca-certificates-mozilla 3.75-1
   198  2022-02-05 14:14:20     lib32-nss 3.75-1
   199  2022-02-05 14:14:20     nss 3.75-1
   200  2022-02-05 16:03:49     python 3.10.2-1
**[steve@Steve-Main ~]$ pip install  git+https://github.com/timothycrosley/streamdeck-ui**

which is up and running for 3.9.9 but not >3.10

Ive highlighted above the relevant packages Ive installed from aur + source.

Not sure how to reverse,     **pip install  git+https://github.com/timothycrosley/streamdeck-ui**

**steve@Steve-Main ~]$ pip uninstall  git+https://github.com/timothycrosley/streamdeck-ui
ERROR: You must give at least one requirement to uninstall (see "pip help uninstall")
[steve@Steve-Main ~]$** 

Thanks I will be installing the OS frequently every couple of months or so, concrete way of 
installing on arch. Is it not simple for you guys to officially publish package to **AUR** 
like you have for other distros, then its as simple as   **pacman -S streamdeck-git**
It would be my preferred way of doing it.

**Comment by dodgyrabbit** [comment]
You should be able to uninstall the normal way, according to [this](https://stackoverflow.com/a/51562882/192815).

```
pip3 uninstall streamdeck-ui
```

You may have to do this multiple times if you have different versions installed.

> You closed the previous one I cant find it to do manual install. Ive done an install from source.
The instructions are on the front page.
https://github.com/timothycrosley/streamdeck-ui

Don't want to state the obvious, but you can also find closed cases by either clicking on the closed link, or `is:closed`.  Perhaps you meant something else.
![image](https://user-images.githubusercontent.com/518187/152650445-b45af0f3-980e-44cb-862c-570f80c11464.png)

**Comment by Data-007** [comment]
Hi Pieter
I am unsure which version I am on, I have "pip3 uninstall streamdeck-ui" plus removed the aur packages.
I have reinstalled using pip3 install streamdeck_ui (eventually, after a few attempts adding sudo....)
But I have no help menu, so I believe, Iam not on the latest version!
I have a machine other than this one that has the help menu.


How to get 1.3.3 and even latter versions when they come?

I think I would like to see is the inclusion of the patch/syttemd service as described, [here](https://github.com/timothycrosley/streamdeck-ui/issues/189#issuecomment-1012631171l) 
Iam away to play with the suggestion above as it takes care of the startup issue I have.


Keep up the hard work and if I can help be sure to holler. Like the sounds of V1.4..... I can beta if you want.
--
Data007

**Comment by dodgyrabbit** [comment]
> I am unsure which version I am on

Use the following command
```
pip3 show streamdeck-ui
```
Once you're on 1.1.3, it gets easier as you can see it in the Help->About
> How to get 1.3.3 and even latter versions when they come?

```
pip3 install --upgrade streamdeck-ui
```
> I have reinstalled using pip3 install streamdeck_ui (eventually, after a few attempts adding sudo....)

Just note that it is `streamdeck-ui` not `streamdeck_ui`
You should *not* use sudo. It can create a lot of confusion because if you do - it will look like it installed, but then it doesn't work when you try run it.

Also note that the installer will put the streamdeck executable in `~/.local/bin`. This may not be in your path, again making it appear like it's not installed. You can review the contents of that directory if you're every unsure.

Can we close this issue out?

**Comment by Data-007** [comment]
Hi once again Pieter.
This is perplexing while installing uninstalling ... Initially I had to do 

**sudo pip3 uninstall streamdeck-ui**

as normal   **pip3 uninstall streamdeck-ui** produced errors and a  lot off red text.....

Anyway now Ive installed  **pip3 install streamdeck-ui**
ad run **pip3 show streamdeck-ui** which reports 

`Name: streamdeck-ui
Version: 1.1.3
`

to be sure Iam running the correct version, I entered

'/home/steve/.local/bin/streamdeck ' which runs streamdeck

However even when running  **streamdeck** or  **/home/steve/.local/bin/streamdeck **
I do NOT get a 'Help' menu, dispite  Version:1.1.3 being reported.

Having used sudo have I got a stuck install some how? Streamdeck-XL in use.

I include the latest run up below..........  I use ZSH hence I think the strange characters.

'steve@Steve-Main  /home/steve   /home/steve/.local/bin/streamdeck                                                22:42:29 

Icon theme "Surfn-Arc" not found.
Icon theme "Surfn" not found.
Icon theme "gnome" not found.
libpng warning: iCCP: known incorrect sRGB profile
/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/api.py:309: UserWarning: AL47J2C06284 has settings specified but is not seen. Likely unplugged!
  warn(f"{deck_id} has settings specified but is not seen. Likely unplugged!")
libpng warning: iCCP: known incorrect sRGB profile
'

**Comment by dodgyrabbit** [comment]
> I do NOT get a 'Help' menu, dispite Version:1.1.3 being reported.

No you are **correct**. It is only in the upcoming version `1.14`. I reviewed the release notes again, my mistake.
So you are on the latest release version now.

OK so besides the warnings you get - does it work now?

**Comment by Data-007** [comment]
Hi Pieter 
Warnings, that was only on the uninstall, unless you mean the run up.
No it works away happily at the moment, pushing buttons giving desired outcome's.

Away to play setting up systemd per the posts linked sever comments above,
Thanks again Pieter

**Comment by Data-007** [comment]
Install log 

`[steve@steve-main bin]$ ls
cairosvg          pyside2-lupdate  pyside2-uic
pyside2-designer  pyside2-rcc      streamdeck
[steve@steve-main bin]$ streamdeck
Waiting for Stream Deck(s)...
Traceback (most recent call last):
  File "/home/steve/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 680, in start
    items = api.open_decks().items()
  File "/home/steve/.local/lib/python3.10/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Devices/StreamDeck.py", line 153, in open
    self.device.open()
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/steve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.`

That's after 

pip3 install streamdeck-ui


The above did not work. So I went and installed from the aur
python-elgato-streamdeck   streamdeck-ui-git

This leaves me on 1.1.3 probably because off the aur packages

Hmm

**Comment by dodgyrabbit** [comment]
@Data-007 Could you open an new issue, with a clear description of the problem, desired outcome, what was tried etc. Sorry I can't keep track of conversational style troubleshooting for everyone anymore. Try looking at it from my view - people just post a log with sparse details. With regards to the error you show - most likely a streamdesk instance is already running. See this: https://github.com/timothycrosley/streamdeck-ui/issues/200#issuecomment-1037254297
