### ISSUE TITLE
qt.qpa.plugin: IOT Instruction (core dump)

### ISSUE THREAD

**Issue by SumNeuron** [timothycrosley/streamdeck-ui#200]
Followed this guide: https://timothycrosley.github.io/streamdeck-ui/#known-issues

```
QFactoryLoader::QFactoryLoader() checking directory path "/home/my_user_name/anaconda3/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/home/my_user_name/anaconda3/plugins/platforms/libqeglfs.so"
Found metadata in lib /home/my_user_name/anaconda3/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 329991
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/home/my_user_name/anaconda3/plugins/platforms/libqminimal.so"
Found metadata in lib /home/my_user_name/anaconda3/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 329991
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/home/my_user_name/anaconda3/plugins/platforms/libqminimalegl.so"
Found metadata in lib /home/my_user_name/anaconda3/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 329991
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/home/my_user_name/anaconda3/plugins/platforms/libqoffscreen.so"
Found metadata in lib /home/my_user_name/anaconda3/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 329991
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/home/my_user_name/anaconda3/plugins/platforms/libqvnc.so"
Found metadata in lib /home/my_user_name/anaconda3/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 329991
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/home/my_user_name/anaconda3/plugins/platforms/libqxcb.so"
Found metadata in lib /home/my_user_name/anaconda3/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 329991
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/my_user_name/anaconda3/bin/platforms" ...
Cannot load library /home/my_user_name/anaconda3/plugins/platforms/libqxcb.so: (/home/my_user_name/anaconda3/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform, version Qt_5_PRIVATE_API)
QLibraryPrivate::loadPlugin failed on "/home/my_user_name/anaconda3/plugins/platforms/libqxcb.so" : "Cannot load library /home/my_user_name/anaconda3/plugins/platforms/libqxcb.so: (/home/my_user_name/anaconda3/plugins/platforms/../../lib/libQt5XcbQpa.so.5: undefined symbol: _ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform, version Qt_5_PRIVATE_API)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, xcb.

[1]    9588 IOT instruction (core dumped)  streamdeck
```

**Comment by SumNeuron** [comment]
How do I get it then to work with  conda?

**Comment by dodgyrabbit** [comment]
Not familiar with it.

**Comment by SumNeuron** [comment]
@dodgyrabbit ok, tried with just python outside of conda

```
Traceback (most recent call last):
  File "/home/solstice/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/solstice/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 675, in start
    items = api.open_decks().items()
  File "/home/solstice/.local/lib/python3.9/site-packages/streamdeck_ui/api.py", line 105, in open_decks
    deck.open()
  File "/home/solstice/.local/lib/python3.9/site-packages/StreamDeck/Devices/StreamDeck.py", line 153, in open
    self.device.open()
  File "/home/solstice/.local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/solstice/.local/lib/python3.9/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.

```

**Comment by SumNeuron** [comment]
@dodgyrabbit 
1. no processes running
2. did that (and also system reboot)
3. rules are:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0060", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0063", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006c", TAG+="uaccess"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="006d", TAG+="uaccess"
```
still same error

**Comment by dodgyrabbit** [comment]
What type of device is it?

**Comment by SumNeuron** [comment]
It is the standard streamdeck

**Comment by dodgyrabbit** [comment]
The standard deck comes in 2 different models. Make sure the line above is added to your udev rules and unplug/replug. Let's try rule out that.

**Comment by SumNeuron** [comment]
Ok that resolved the issue, but now I found a different weird behavior. 
I click a button on the streamdeck and sometimes it registers as "Action #" depending on the button I pressed. Othertimes it doesnt register at all.

**Comment by dodgyrabbit** [comment]
Let's close the issue as the original problem is solved.
Please review old cases and see if there's something there to help you.
If not, open a new case - provide as much detail, version, OS, context, steps to reproduce, settings file, screenshots etc. Anything that will help troubleshoot this easier.
