### ISSUE TITLE
streamdeck-ui not starting

### ISSUE THREAD

**Issue by radstevee** [timothycrosley/streamdeck-ui#205]
Hello, i just installed it on my Garuda (Arch) Machine and when i try to start it, it gives me this error: 
`Traceback (most recent call last):
File "/home/radsteve/.local/bin/streamdeck", line 8, in <module>
sys.exit(start())
File "/home/radsteve/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 675, in start
items = api.open_decks().items()
File "/home/radsteve/.local/lib/python3.10/site-packages/streamdeck_ui/api.py", line 105, in open_decks
deck.open()
File "/home/radsteve/.local/lib/python3.10/site-packages/StreamDeck/Devices/StreamDeck.py", line 153, in open
self.device.open()
File "/home/radsteve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, inopen
self.device_handle = self.hidapi.open_device(self.device_info['path'])
File "/home/radsteve/.local/lib/python3.10/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, inopen_device
raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.`
I did the part of adding it to the udev rules. 

EDIT: Fixed 
it was on a usb hub and i just put it in a normal usb port

**Comment by dodgyrabbit** [comment]
Can you clarify - did you find the problem? If so - can you elaborate and close the case?
