### ISSUE TITLE
Removing a device

### ISSUE THREAD

**Issue by gregfr** [timothycrosley/streamdeck-ui#230]
**Describe the bug**
Removing a first device after adding a second one and the software doesn't see any of them.

**To Reproduce**
1. I was using a Streamdeck 15 keys
2. I added a Streamdeck 32 keys
3. I configured it, everything was working ok
4. I removed the first device
5. I restarted the software and the device menu is empty

**Expected behavior**
The device menu contains the connected device

**Screenshots**
If applicable, add screenshots, pictures or video to help explain your problem.

**Operating system (please complete the following information)**
 - OS: Ubuntu 19.10
 - Desktop environment: KDE
 - Python version 2.7.17 / 3.7.5

**Stream Deck Version**
 - Standard, XL

**Comment by gregfr** [comment]
streamdeck-ui version 2.0.3
streamdeck 0.9.0
pyside2 5.15.2
pillow 9.1.0
pyinput 1.7.4

**Comment by gregfr** [comment]
I tried removing the old config part from `~/.streamdeck_ui.json`, same.

When run from cli, I got this:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/greg/.local/lib/python3.8/site-packages/streamdeck_ui/stream_deck_monitor.py", line 86, in _run
    self.attached(streamdeck_id, streamdeck)
  File "/home/greg/.local/lib/python3.8/site-packages/streamdeck_ui/api.py", line 177, in attached
    streamdeck.open()
  File "/home/greg/.local/lib/python3.8/site-packages/StreamDeck/Devices/StreamDeck.py", line 153, in open
    self.device.open()
  File "/home/greg/.local/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 352, in open
    self.device_handle = self.hidapi.open_device(self.device_info['path'])
  File "/home/greg/.local/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 181, in open_device
    raise TransportError("Could not open HID device.")
StreamDeck.Transport.Transport.TransportError: Could not open HID device.

```

**Comment by dodgyrabbit** [comment]
No response. See #250 in case it helps. Closing.
