### ISSUE TITLE
Failed to launch on Ubutu Budgie 22.04

### ISSUE THREAD

**Issue by Iwifia** [timothycrosley/streamdeck-ui#260]
When launching streamdeck after a manual install on Ubuntu Budgie 22.04 I recieve the following error. Python version is 3.10.

```
Traceback (most recent call last):
  File "/home/user/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/home/user/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 11, in <module>
    from pynput import keyboard
  File "/home/user/.local/lib/python3.10/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/user/.local/lib/python3.10/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/user/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```

**Comment by dodgyrabbit** [comment]
The library pynput that is used to simulate keystrokes requires an X server. Likely your install does not use X./
Some more info here: 
https://pynput.readthedocs.io/en/latest/limitations.html#linux
