### ISSUE TITLE
After upgrade to Fedora 37, streamdeck-ui can't open SVG files

### ISSUE THREAD

**Issue by RodneyBrown** [timothycrosley/streamdeck-ui#273]
After re-installing streamdeck-ui with pip3, I now get the following error when it reads my config file:

```
/home/rbrown/.local/lib/python3.11/site-packages/streamdeck_ui/api.py:258: UserWarning: AL06L2C56837 has settings specified but is not seen. Likely unplugged!
  warn(f"{deck_id} has settings specified but is not seen. Likely unplugged!")
Traceback (most recent call last):
  File "/home/rbrown/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/home/rbrown/.local/lib/python3.11/site-packages/streamdeck_ui/gui.py", line 281, in start
    api.render()
  File "/home/rbrown/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 269, in render
    image = _render_key_image(deck, **button_settings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rbrown/.local/lib/python3.11/site-packages/streamdeck_ui/api.py", line 280, in _render_key_image
    rgba_icon = Image.open(icon).convert("RGBA")
                ^^^^^^^^^^^^^^^^
  File "/home/rbrown/.local/lib/python3.11/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file '/home/rbrown/Pictures/Stream Deck/Apps/firefox.svg'
```

**Comment by RodneyBrown** [comment]
Looks like this is a problem on my system installing via pip3.  It's installing a very old version of streamdeck-ui (1.0.2) where Pypi.org shows the version is now 2.0.6.
