### ISSUE TITLE
Installation on Raspberry Pi OS (32bit)

### ISSUE THREAD

**Issue by cb2-dd** [timothycrosley/streamdeck-ui#276]
**Describe the bug**
Debian Install Script running on Raspberry Pi 3 with Raspberry Pi OS (32bit) based on Debian bullseye seems to be installed correctly but a start of *streamdeck* results in errors:
```
user@raspberrypi:~ $ streamdeck
Traceback (most recent call last):
  File "/home/user/.local/bin/streamdeck", line 8, in <module>
    sys.exit(start())
  File "/home/user/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 185, in start
    build_buttons(ui, ui.cards.currentWidget())
  File "/home/user/.local/lib/python3.9/site-packages/streamdeck_ui/gui.py", line 97, in build_buttons
    deck = api.get_deck(deck_id)
  File "/home/user/.local/lib/python3.9/site-packages/streamdeck_ui/api.py", line 73, in get_deck
    return {"type": decks[deck_id].deck_type(), "layout": decks[deck_id].key_layout()}
KeyError: None
```

**To Reproduce**
1. Install current Raspberry Pi OS (32bit) on a Raspberry Pi 3
2. Install streamdeck_ui from [Debian/Ubuntu install script](https://github.com/timothycrosley/streamdeck-ui/blob/master/scripts/ubuntu_install.sh)
3. Start *streamdeck*

**Operating system (please complete the following information)**
 - Raspberry Pi OS (32bit) bullseye
 - Desktop environment: OpenBox
 - Python 3.9

**Stream Deck Version**
 - Standard MK.2

**Comment by ianfloats** [comment]
I got this error on Ubuntu 18.04 when starting the app *without Streamdeck hardware*.

I looked into it a little.

The error "KeyError: None" is triggered by this line, when deck_id is "None":
> return {"type": decks[deck_id].deck_type(), "layout": decks[deck_id].key_layout()}

Because of the dictionary access:
> decks[deck_id] 

It seems the UI requires a device to be present to start.

So I wonder if your hardware is not detected or your user account doesn't have rights to access it.

**Comment by ianfloats** [comment]
Since my last comment I received a streamdeck device, and still saw the error, so my previous speculation was wrong.  The UI can indeed start without a device present.

I got it running by installing and using a newer version of python than is the default on my (older) ubuntu.

```
$ python -V
Python 2.7.17

$ python3.8 -V
Python 3.8.0
```

I ran the setup commands using python3.8 and changed the first line of the startup script at [~/.local/bin/streamdeck](https://github.com/timothycrosley/streamdeck-ui/issues/~/.local/bin/streamdeck) to use python3.8 instead.

**Comment by 4s3ti** [comment]
hi, this project seems to be stale and a new fork as been made with the intention of replacing this one.

if this still an issue please reopen it at: https://github.com/streamdeck-linux-gui/streamdeck-linux-gui
