### ISSUE TITLE
StreamDeck Crashing, Board no longer responsive

### ISSUE THREAD

**Issue by airfield20** [timothycrosley/streamdeck-ui#28]
After running for a bit of time, buttons will stop working and this message appears in the terminal that I've run streamdeck-ui in.
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2020-01-30 18:51:28,270 [  71550]   WARN - brains.cidr.execution.debugger - >kill
2020-01-30 18:51:28,270 [  71550]   WARN - brains.cidr.execution.debugger - <^error,msg="The program is not being run."
```

**Comment by airfield20** [comment]
Im running this on regolith linux. Regular ubuntu with i3wm installed and some other supporting tools.

**Comment by Anthonyjmartin** [comment]
I am getting something similar.
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ajm030/.local/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeck.py", line 90, in _read
    self.key_callback(self, k, new)
  File "/home/ajm030/.local/lib/python3.7/site-packages/streamdeck_ui/api.py", line 43, in _key_change_callback
    keyboard.type(write)
  File "/home/ajm030/.local/lib/python3.7/site-packages/pynput/keyboard/_base.py", line 460, in type
    from .. import _CONTROL_CODES
ImportError: cannot import name '_CONTROL_CODES' from 'pynput' (/home/ajm030/.local/lib/python3.7/site-packages/pynput/__init__.py)`

**Comment by dodgyrabbit** [comment]
An updated version will be published in the next few weeks. Please keep an eye out, and if you still have this issue, please reopen so we can investigate. Thanks!
