### ISSUE TITLE
openSUSE Tumbleweed (Gnome X11) doesn't launch streamdeck-ui. (KDE worked normally)

### ISSUE THREAD

**Issue by v3eil** [timothycrosley/streamdeck-ui#292]
Worked perfectly in openSUSE Tumbleweed KDE but I did fresh install with GNOME desktop and now it won't start. I have always used the precooked fedora script.

```
Traceback (most recent call last):
  File "/home/XXXXXX/.local/bin/streamdeck", line 5, in <module>
    from streamdeck_ui.gui import start
  File "/home/XXXXXX/.local/lib/python3.10/site-packages/streamdeck_ui/gui.py", line 11, in <module>
    from pynput import keyboard
  File "/home/XXXXXX/.local/lib/python3.10/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/XXXXXX/.local/lib/python3.10/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/XXXXXX/.local/lib/python3.10/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```

**Operating system (please complete the following information)**
 - OS: openSUSE Tumbleweed
 - Desktop environment: Gnome 43.2 (X11)
 - Python Version 3.10.9

**Stream Deck Version**
- XL

**Comment by rombert** [comment]
Try running something like `xhost +`,in in the same terminal, first.

**Comment by dodgyrabbit** [comment]
Please upgrade to 2.0.13 and try again. Reopen this issue but it should resolve the issue above. It will *not* resolve Wayland issues but it should run.
