### ISSUE TITLE
Suddenly stopped working: Exception in thread-1 (_run)

### ISSUE THREAD

**Issue by irthomasthomas** [timothycrosley/streamdeck-ui#315]
Hi, v 2.0.15 suddenly stopped working on me. It launches, but everything is blank.

Manjaro 22.1
KDE Plasma 5.27.3
Kernel 6.1.21
Python 3.10

Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1713, in feed
    self.parser.Parse(data, False)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/stream_deck_monitor.py", line 113, in _run
    self.attached(streamdeck_id, streamdeck)
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/api.py", line 188, in attached
    self.update_streamdeck_filters(serial_number)
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/api.py", line 479, in update_streamdeck_filters
    self.update_button_filters(serial_number, page, button)
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/api.py", line 514, in update_button_filters
    display_handler.replace(page, button, filters)
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/display/display_grid.py", line 79, in replace
    filter.initialize(self.size)
  File "/usr/lib/python3.10/site-packages/streamdeck_ui/display/image_filter.py", line 32, in initialize
    png = cairosvg.svg2png(svg_code, output_height=size[1], output_width=size[0])
  File "/usr/lib/python3.10/site-packages/cairosvg/__init__.py", line 55, in svg2png
    return surface.PNGSurface.convert(
  File "/usr/lib/python3.10/site-packages/cairosvg/surface.py", line 127, in convert
    tree = Tree(
  File "/usr/lib/python3.10/site-packages/cairosvg/parser.py", line 390, in __init__
    tree = ElementTree.fromstring(
  File "/usr/lib/python3.10/site-packages/defusedxml/common.py", line 126, in fromstring
    parser.feed(text)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1715, in feed
    self._raiseerror(v)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1622, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by irthomasthomas** [comment]
Solved. I had dragged an icon from my menu and this was causing the error.
