### ISSUE TITLE
Stopped working with Mini

### ISSUE THREAD

**Issue by s01itude** [timothycrosley/streamdeck-ui#35]
When I first used this everything was working fine, but now when I try to run it i get 

`Traceback (most recent call last):
  File "/home/s01itude/.local/bin/streamdeck", line 10, in <module>
    sys.exit(start())
  File "/home/s01itude/.local/lib/python3.7/site-packages/streamdeck_ui/gui.py", line 281, in start
    api.render()
  File "/home/s01itude/.local/lib/python3.7/site-packages/streamdeck_ui/api.py", line 271, in render
    deck.set_key_image(button_id, image)
  File "/home/s01itude/.local/lib/python3.7/site-packages/StreamDeck/Devices/StreamDeckMini.py", line 133, in set_key_image
    raise IndexError("Invalid key index {}.".format(key))
IndexError: Invalid key index 7.
`

If I unplug my mini and leave my standard plugged in it works. I've tried uninstalling/reinstalling, changing hid dependencies, replugging, and rebooting to no avail.

**Comment by dodgyrabbit** [comment]
Hi there, looking at the error, likely there is something wrong with the settings file (in your home directory, called `.streamdeck_ui.json`).

Make a copy of it for yourself and then delete it. Try running again. 

If it works - please feel free to attach the "bad" settings file and I'll take a look. Make sure there isn't any sensitive information in there before you post it.
