### ISSUE TITLE
Error running streamdeck-ui on Fedora

### ISSUE THREAD

**Issue by devrimgunduz** [timothycrosley/streamdeck-ui#48]
Hi,

I'm getting this while running streamdeck on Fedora 31. Any ideas?
```

Traceback (most recent call last):
  File "/home/devrim/.local/bin/streamdeck", line 10, in <module>
    sys.exit(start())
  File "/home/devrim/.local/lib/python3.7/site-packages/streamdeck_ui/gui.py", line 269, in start
    build_device(ui)
  File "/home/devrim/.local/lib/python3.7/site-packages/streamdeck_ui/gui.py", line 199, in build_device
    build_buttons(ui, page)
  File "/home/devrim/.local/lib/python3.7/site-packages/streamdeck_ui/gui.py", line 129, in build_buttons
    deck = api.get_deck(deck_id)
  File "/home/devrim/.local/lib/python3.7/site-packages/streamdeck_ui/api.py", line 133, in get_deck
    return {"type": decks[deck_id].deck_type(), "layout": decks[deck_id].key_layout()}
KeyError: None
```
Thanks!

**Comment by mwcz** [comment]
I see the same error on Fedora 30.

**Comment by devrimgunduz** [comment]
Works on F-32, so closing.
