### ISSUE TITLE
Module not found - Ubuntu 18.04     5.4.0.54 -generic

### ISSUE THREAD

**Issue by Werks-cpu** [timothycrosley/streamdeck-ui#78]
After a manual install. The program won't start:

xxx@xxxx:~$ streamdeck
Traceback (most recent call last):
  File "/home/pete/.local/bin/streamdeck", line 7, in <module>
    from streamdeck_ui.gui import start
ModuleNotFoundError: No module named 'streamdeck_ui'

**Comment by Werks-cpu** [comment]
Here's some additional info:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.6/distutils/command/install.py", line 351, in finalize_options
    self.create_home_path()
  File "/usr/lib/python3.6/distutils/command/install.py", line 581, in create_home_path
    os.makedirs(path, 0o700)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/pete/.local/lib/python3.6'

**Comment by Werks-cpu** [comment]
I had this running once, but lost an HD.  Reloaded with Clonezilla, but the clone was from just before we installed the  
"Stream Deck".  It's almost like it can't find "streamdeck_ui.gui"

Below is the content of /home/pete/.local/bin/streamdeck 

#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from streamdeck_ui.gui import start
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(start())


  Please help, not that familar with Linux

**Comment by Werks-cpu** [comment]
The directory '/home/pete/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/pete/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: streamdeck_ui in ./.local/lib/python3.6/site-packages
Requirement already satisfied: streamdeck<0.7.0,>=0.6.3 in ./.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: hidapi<0.8.0,>=0.7.99 in ./.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: pillow<7.0,>=6.1 in ./.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: pyside2<6.0,>=5.13 in ./.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: pynput<2.0,>=1.4 in ./.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3/dist-packages (from hidapi<0.8.0,>=0.7.99->streamdeck_ui)
Requirement already satisfied: shiboken2==5.15.2 in ./.local/lib/python3.6/site-packages (from pyside2<6.0,>=5.13->streamdeck_ui)
Requirement already satisfied: evdev>=1.3; "linux" in sys_platform in ./.local/lib/python3.6/site-packages (from pynput<2.0,>=1.4->streamdeck_ui)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in ./.local/lib/python3.6/site-packages (from pynput<2.0,>=1.4->streamdeck_ui)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynput<2.0,>=1.4->streamdeck_ui)

$ sudo -H pip3 install streamdeck_ui

Requirement already satisfied: streamdeck_ui in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: pyside2<6.0,>=5.13 in /root/.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: pillow<7.0,>=6.1 in /root/.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: streamdeck<0.7.0,>=0.6.3 in /root/.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: pynput<2.0,>=1.4 in /root/.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: hidapi<0.8.0,>=0.7.99 in /root/.local/lib/python3.6/site-packages (from streamdeck_ui)
Requirement already satisfied: shiboken2==5.15.2 in /root/.local/lib/python3.6/site-packages (from pyside2<6.0,>=5.13->streamdeck_ui)
Requirement already satisfied: python-xlib>=0.17; "linux" in sys_platform in /root/.local/lib/python3.6/site-packages (from pynput<2.0,>=1.4->streamdeck_ui)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynput<2.0,>=1.4->streamdeck_ui)
Requirement already satisfied: evdev>=1.3; "linux" in sys_platform in /root/.local/lib/python3.6/site-packages (from pynput<2.0,>=1.4->streamdeck_ui)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3/dist-packages (from hidapi<0.8.0,>=0.7.99->streamdeck_ui)

pete@Viper:~$ streamdeck
Traceback (most recent call last):
  File "/home/pete/.local/bin/streamdeck", line 7, in <module>
    from streamdeck_ui.gui import start
ModuleNotFoundError: No module named 'streamdeck_ui'
pete@Viper:~$

**Comment by Werks-cpu** [comment]
Product must no longer be active or supported

**Comment by Werks-cpu** [comment]
Could not obtain help.
